module QuestModule
  # You don't actually need to add any information, but the respective fields in the UI will be blank or "???"
  # I included this here mostly as an example of what not to do, but also to show it's a thing that exists
  Quest1 = {
    :ID => "1",
    :Name => "Your Journey",
    :QuestDescription => "Make your way through Parthenia and complete the Gym Challenge!",
    :Stage1 => "Head to the Trainer's Institute.",
    :Stage2 => "Head to Boro Town.",
    :Stage3 => "Speak with Bruce of OffCorp.",
    :Stage4 => "Challenge the Gym.",
    :Stage5 => "Follow the Miltia Member.",
    :Stage6 => "Head to the next town.",
    :Stage7 => "Find out what OffCorp is after.",
    :Stage8 => "Challenge the Gym.",
    :Stage9 => "Head toward Neonn Town.",
    :Stage10 => "Investigate the abandoned DefCorp building.",
    :Stage11 => "Challenge the Gym.",
    :Stage12 => "Explore Mt. Nenox from the Neonn entrance.",
    :Stage13 => "Find the hidden cave, then head to Sodum Town.",
    :Stage14 => "Go explore the Army Base.",
    :Stage15 => "Go to the Army Main Office.",
    :Stage16 => "Follow the Officer.",
    :Stage17 => "Escape from Army Prison",
    :Stage18 => "Challenge the Gym.",
    :Stage19 => "Follow Gordon to the Naval Base.",
    :Stage20 => "Investigate the Naval Base.",
    :Stage21 => "Meet up with Eugene.",
    :Stage22 => "Challenge the Gym.",
    :Stage23 => "Meet Winslow in the Potion Plant.",
    :Stage24 => "Follow Winslow through the hidden lab.",
    :Stage25 => "Pass through Lake Chloros to go toward Nitro City.",
    :Stage26 => "Meet with Turner in Trainer's Institute.",
    :Stage27 => "Make your way to Carbo Valley.",
    :Stage28 => "Speak to Joseph.",
    :Stage29 => "Challenge the Gym.",
    :Stage30 => "Help save the Underground Village.",
    :Stage31 => "Investigate Abandoned Warehouse.",
    :Stage32 => "Speak to Joseph.",
    :Stage33 => "Go after Rotom! It's being taken to the Capitol!",
    :Stage34 => "Go to the Guard Base.",
    :Stage35 => "Follow Sunni to the Secret Lab.",
    :Stage36 => "Challenge the Gym.",
    :Stage37 => "Speak to Armand.",
    :Stage38 => "Infiltrate the Capitol and find Joseph.",
    :Stage39 => "Meet with Armand.",
    :Stage40 => "Challenge the Gym.",
    :Stage41 => "Make your way to Route 18.",
    :Stage42 => "Check in with Winston's friends.",
    :Stage43 => "Meet Rotom at the Abandoned Space Station.",
    :Stage44 => "Battle Rotom.",
    :Stage45 => "Go to the Pokémon League.",
    :Stage46 => "Stop the Chancellor.",
    :Stage47 => "Meet with Joseph.",
    :Stage48 => "Explore Helum Mine.",
    :Stage49 => "Begin your search for Bruce of OffCorp.",
    :Stage50 => "Find where Bruce is talking about in his note.",
    :Stage51 => "Go to DefCorp to look for Jackson.",
    :Stage52 => "Find where the guard is talking about.",
    :Stage53 => "Find the other 3 chambers across Parthenia.",
    :Stage54 => "Meet Joseph.",
    :Stage55 => "Find the Dojo Master.",
    :Stage56 => "Challenge the Dojo.",
    :Stage57 => "Head toward Plumbum Town",
    :Stage58 => "Defeat the PsyCorp Scientists.",
    :Stage59 => "Defeat Sylvester.",
    :Stage60 => "Go to Argyros City.",
    :Stage61 => "Help stop the Army!",
    :Stage62 => "Challenge the Dojo",
    :Stage63 => "Wait for the next update!",
    :Location1 => "Garon Town",
    :Location2 => "Boro Town",
    :Location3 => "Boro Town",
    :Location4 => "Helum City",
    :Location5 => "Helum City",
    :Location6 => "Ogan City",
    :Location7 => "Mt. Nenox",
    :Location8 => "Ogan City",
    :Location9 => "Helum Tunnel",
    :Location10 => "Neonn Town",
    :Location11 => "Neonn Town",
    :Location12 => "Mt. Nenox",
    :Location13 => "Darkfire Cave",
    :Location14 => "Sodum Town",
    :Location15 => "Sodum Town",
    :Location16 => "Army Base",
    :Location17 => "Army Base",
    :Location18 => "Krypto Quay",
    :Location19 => "Hydro Island",
    :Location20 => "Hydro Island",
    :Location21 => "Krypto Quay",
    :Location22 => "Chloros City",
    :Location23 => "Potion Plant",
    :Location24 => "Potion Plant",
    :Location25 => "Lake Chloros",
    :Location26 => "Garon Town",
    :Location27 => "Carbo Valley",
    :Location28 => "Mangan Village",
    :Location29 => "Nitro City",
    :Location30 => "Underground Village",
    :Location31 => "Underground Village",
    :Location32 => "Underground Village",
    :Location33 => "Rubid Outpost",
    :Location34 => "Oxy Town",
    :Location35 => "Lake Chloros",
    :Location36 => "The Capitol",
    :Location37 => "The Capitol",
    :Location38 => "The Capitol",
    :Location39 => "Rubid Outpost",
    :Location40 => "Zirco Mountain",
    :Location41 => "Carbo Valley",
    :Location42 => "Rado Foothills",
    :Location43 => "Victory Road",
    :Location44 => "Abandoned Space Station",
    :Location45 => "Pokémon League",
    :Location46 => "Pokémon League",
    :Location47 => "Helum City",
    :Location48 => "Helum Mine",
    :Location49 => "Boro Town",
    :Location50 => "???",
    :Location51 => "Chloros City",
    :Location52 => "???",
    :Location53 => "???",
    :Location54 => "Oxy Town",
    :Location55 => "Ferro Village",
    :Location56 => "Lithum Port",
    :Location57 => "Route 23",
    :Location58 => "Plumbum Town",
    :Location59 => "Plumbum Ruins",
    :Location60 => "Argyros City",
    :Location61 => "Argyros Observatory",
    :Location62 => "Argyros City",
    :Location63 => "Stannum Town"
  }

#====================================
  Quest2 = {
    :ID => "2",
    :Name => "Lost in the Woods",
    :QuestDescription => "Find the lost little boy!",
    :Stage1 => "Find the woman's son.",
    :Location1 => "Garon Woods"
  }

  #====================================
    Quest3 = {
      :ID => "3",
      :Name => "Wrong Kind of Hike",
      :QuestDescription => "Find the lost Clefairy!",
      :Stage1 => "Find the woman's Clefairy.",
      :Location1 => "Nenox Caverns"
    }

  #====================================
    Quest4 = {
      :ID => "4",
      :Name => "Chill Out",
      :QuestDescription => "Find the lost child!",
      :Stage1 => "Find the man's daughter.",
      :Location1 => "Mt. Nenox"
    }

    #====================================
    Quest5 = {
      :ID => "5",
      :Name => "Shop til You Drop",
      :QuestDescription => "Find the lost child!",
      :Stage1 => "Go to Neonn PMC to find the woman's son.",
      :Stage2 => "Follow the boy.",
      :Location1 => "Neonn Town",
      :Location2 => "Route 4"
    }
    #====================================
    Quest6 = {
      :ID => "6",
      :Name => "Her Precious",
      :QuestDescription => "Find the lost Riolu!",
      :Stage1 => "Find the woman's Riolu.",
      :Location1 => "Route 12 or 13"
    }
    #====================================
    Quest7 = {
      :ID => "7",
      :Name => "The Secret Stone",
      :QuestDescription => "Find the Rare Stone!",
      :Stage1 => "Find the Rare Stone.",
      :Stage2 => "Take Rare Stone back to Scientist.",
      :Location1 => "Cobalt Cave",
      :Location2 => "Nitro City"
    }
end
